### ISSUE TITLE
Error generating the sitemap

### ISSUE THREAD

**Issue by benfolds** [jb-support/multiple-sitemaps#1]
Hi,

in my installation there is an error generating the sitemap. 

```
Uncaught PHP Exception ErrorException: "Warning: Attempt to read property "id" on array" at ROOT/vendor/jb-support/multiple-sitemaps/src/Controller/MultipleSitemapController.php line 76
```

The Line
`$tags[] = 'jb.sitemap.' . $jbSitemap->id;`

is working this way, as $jbSitemap is an array:
`$tags[] = 'jb.sitemap.' . $jbSitemap['id'];`

Is this bundle still active and maintained? i would appriciate it :)

**Comment by syntaxys** [comment]
I got also an error:
... Argument #1 ($value) must be of type int, string given, called in ../contao-413-lts.php80/vendor/jb-support/multiple-sitemaps/src/Controller/MultipleSitemapController.php on line 110 at ../contao-413-lts.php80/vendor/symfony/http-foundation/Response.php:811)"} []

Solution:
$response->setSharedMaxAge($jbSitemap["maxAge"]);
should be
$response->setSharedMaxAge((int)$jbSitemap["maxAge"]);

**Comment by Flo-JB** [comment]
Thank you for your reports.
I fixed both things and released a new version.
