### ISSUE TITLE
Uncaught PHP Exception Symfony

### ISSUE THREAD

**Issue by mandrael** [jb-support/multiple-sitemaps#6]
Als ich nach der Installation die erste Sitemap anlegen wollte, kam ein Server Error. Hier ist das, was im Debug-Mode im Log unter critical zu finden war:

–
Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "FaqCategoryModel" from namespace "Contao". Did you forget a "use" statement for another namespace?" at /home/nkinstitute/web/nkinstitute.at/public_html/vendor/jb-support/multiple-sitemaps/src/Resources/contao/dca/tl_jb_sitemap.php line 322{     "exception": {} }
–

Die Datenbank ist aktuell. Ich verwende die neueste Contao 4.13 
Nebenbei verwende ich nicht alle Contao Module. FAQ habe ich nicht aktiv.

**Comment by Flo-JB** [comment]
Hallo mandrael,

ja in dem Fall macht die Fehlermeldung Sinn. Da müssen wir einen Check einbauen, falls News/FAQs/Events nicht mit geladen werden.
Ein Update können wir voraussichtlich im Laufe der Woche bereitstellen.
